{
 "title": "Cardano Relay-1",
 "description": "Cardano relay one running in Docker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Transactions in Mem pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int"
    }
   ]
  },
  {
   "title": "Epoc",
   "type": "stat",
   "description": "Current epoc",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Mem Pool TX/Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{job=~\"$jobs\"}"
    },
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Mem_resident_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Stat_cputicks_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Processed Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "TX in MemPool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Mem Pool Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "description": "Slot in epoc",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{job=~\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Density",
   "type": "stat",
   "description": "Density",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{job=~\"$jobs\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}